export const products = [
    {
        id: 1,
        title: "Samsung S21",
        description: "black in color",
        price: "2500",
        img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
    {
        id: 2,
        title: "M21",
        description: "white in color",
        price: "2300",
        img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
    {
        id: 3,
        title: "REALME",
        description: "black in color",
        price: "45000",
        img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 4,
        title: "Iphone 12",
        description: "Best mobile ever",
        price: "12",
        img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 5,
        title: "Oppo",
        description: "red in color",
        price: "215478",
        img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
    {
        id: 6,
        title: "Redmi 19",
        description: "black in color",
        price: "500",
        img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 7,
        title: "Samsung ultra",
        description: "black in color",
        price: "65124",
        img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
    {
        id: 8,
        title: "Iphone 15",
        description: "Best mobile ever",
        price: "78956",
        img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 9,
        title: "POCO",
        description: "black in color",
        price: "25000",
        img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
];